name: googleapis_client_dart
description: googleapis_client_dart library for make your program dart more easy.
version: 0.0.0
repository: https://github.com/azkadev/azkadev.git
issue_tracker: https://github.com/azkadev/azkadev.git
homepage: https://youtube.com/@azkadev


executables:
  googleapis_client_dart: googleapis_client_dart
  

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.2
  galaxeus_lib: ^0.0.66
  path: ^1.8.2
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  msix: ^3.12.1
  packagex: ^0.0.25
  test: ^1.24.2

msix_config: 
  display_name: googleapis_client_dart
  install_certificate: false
  # publisher_display_name: Azkadev
  # identity_name: org.azkadev.googleapis_client_dart
  # msix_version: 0.0.0.0
  # capabilities: internetClient, location, microphone, webcam

packagex:
  name: googleapis_client_dart
  dart_target: googleapis_client_dart
  flutter_target: main
  dart_name: googleapis_client_dart
  flutter_name: googleapis_client_dart
  flutter_commands:
    obfuscate: true
    split-debug-info: 0.0.5
  
